name: build and deploy release
on:
  release:
    types: [published]
jobs:
  build:
    if: github.repository == 'QW-Group/qwfwd'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
       target: [linux-amd64, linux-i686, linux-armhf, linux-aarch64, windows-x64, windows-x86]
       include:
         - target: linux-amd64
           os: linux
           arch: amd64
           build-image: debian:stable
           ext: ""
         - target: linux-i686
           os: linux
           arch: i686
           build-image: debian:stable
           ext: ""
         - target: linux-armhf
           os: linux
           arch: armhf
           build-image: debian:stable
           ext: ""
         - target: linux-aarch64
           os: linux
           arch: aarch64
           build-image: debian:stable
           ext: ""
         - target: windows-x64
           os: windows
           arch: x64
           build-image: debian:stable
           ext: ".exe"
         - target: windows-x86
           os: windows
           arch: x86
           build-image: debian:stable
           ext: ".exe"
    container: ${{ matrix.build-image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare Build Environemnt
        shell: bash
        run: |
             apt-get update
             apt-get -y install build-essential cmake gcc-i686-linux-gnu openssh-client
             apt-get -y install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross gcc-aarch64-linux-gnu libc6-dev-arm64-cross
             apt-get -y install gcc-mingw-w64-x86-64 gcc-mingw-w64-i686
      - name: Build
        run: |
             ./build_cmake.sh ${{ matrix.target }}
      - name: Create checksum
        run: |
             md5sum build/${{ matrix.target }}/qwfwd${{ matrix.ext }} > build/${{ matrix.target }}/qwfwd.md5
      - name: Setup SSH
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: Set date
        shell: bash
        run: |
          echo "DATE=$(TZ="Europe/Amsterdam" date "+%Y%m%d-%H%M%S")" >> $GITHUB_ENV
      - name: Deploy
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
             mkdir -p upload/releases/${{ github.ref_name }}/${{ matrix.os }}/${{ matrix.arch }}
             mkdir -p upload/releases/latest/${{ matrix.os }}/${{ matrix.arch }}
             cp build/${{ matrix.target }}/qwfwd${{ matrix.ext }} upload/releases/${{ github.ref_name }}/${{ matrix.os }}/${{ matrix.arch }}/qwfwd${{ matrix.ext }}
             cp build/${{ matrix.target }}/qwfwd.md5 upload/releases/${{ github.ref_name }}/${{ matrix.os }}/${{ matrix.arch }}/qwfwd.md5
             cp build/${{ matrix.target }}/qwfwd${{ matrix.ext }} upload/releases/latest/${{ matrix.os }}/${{ matrix.arch }}/qwfwd${{ matrix.ext }}
             cp build/${{ matrix.target }}/qwfwd.md5 upload/releases/latest/${{ matrix.os }}/${{ matrix.arch }}/qwfwd.md5
             sftp -rp -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile /dev/null' -P ${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:/releases <<< $'put -rp upload/releases/*'
